logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.de.scacap.webcrawler=INFO
google.custom.search.baseUrl=https://www.googleapis.com/customsearch/v1?key={key}&cx={cx}&q={q}
google.custom.search.apiKey=AIzaSyC2FgOoKH7VWfb8cPzR5GUohK7cwxrmUeI
google.custom.search.engineId=002255084212443880508:qvqlxgne9sc
google.custom.search.connectTimeout=3000
google.custom.search.readTimeout=3000